[application]

# App (Project) Name
name = "dx-rpg"

# resource (assets) file folder
asset_dir = "assets"

[web.app]

# HTML title tag content
title = "dx-rpg"

# include `assets` in web platform
[web.resource]

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
