on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

name: Upload Release Asset

permissions:
  contents: write

jobs:
  build:
    name: Upload Release Asset (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update rust
        run: rustup update stable

      - name: Install dioxus-cli
        run: |
          cargo install cargo-binstall
          cargo binstall dioxus-cli@0.7.6 --force
        shell: bash

      - name: Make bundle script executable (Linux only)
        if: runner.os == 'Linux'
        run: chmod +x ./scripts/bundle_app.sh

      - name: Build project
        run: ./scripts/bundle_app.sh
        shell: bash

      - name: Zip bundle
        run: |
          zip -r bundle_${{ matrix.os == 'windows-latest' && 'windows' || 'linux' }}.zip dx-rpg_${{ matrix.os == 'windows-latest' && 'windows' || 'linux' }}
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bundle_${{ matrix.os == 'windows-latest' && 'windows' || 'linux' }}.zip
          path: bundle_${{ matrix.os == 'windows-latest' && 'windows' || 'linux' }}.zip

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: List artifacts
        run: ls -R artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/**/*.zip